### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by lucasgrelaud** [brewswain/blee-commerce#2]
Hi,
I noticed you've left sensitive information in the following file;
 - [Firebase credentials]https://github.com/brewswain/blee-commerce/blob/master/src/firebase/firebase.utils.js)

This may lead to a security issue in your app, so you should remove these informations from your repository.

Regards,
Lucas GRELAUD

**Comment by brewswain** [comment]
Thanks for the heads up, api keys reset and moved from this repo
